[package]
name = "rustos"
version = "0.1.0"
edition = "2018"
authors = ["Pablo Rodríguez <prlf505@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bootloader = "0.9.23"
