# Recompile core and the standard library crates on demand

[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins"]

[build]
# Avoid using the --target flag when building
target = "x86_64-rustos.json"

[target.'cfg(target_os = "none")']
# Run qemu
runner = "bootimage runner"
